version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    volumes:
      - "/home/hajra/localstack_data:/tmp/localstack"  # Replace ~ with the full path

